### PR TITLE
Update indexManager.js

### PR DESCRIPTION
**Pull request by Yamboy1**

### CODE REVIEW

**Comment by Yamboy1** [comment]
Note that this might break on older versions of ie 😢

**Comment by Icedude907** [comment]
I'll check it soon

**Comment by Icedude907** [comment]
"let" is only partially supported on older IOS versions... (<10.4)

**Comment by Icedude907** [comment]
Hi man.
I tried it on my phone (running the latest chrome so it is legit) and the commit seems to have broken the ability to click as well as stopping the settings gear staying white while mousing over the settings box.
Declining and closing the pull request for now.

**Comment by Icedude907** [comment]
Thanks for that though.
I found a alternative and am committing that instead

**Pull request closed without merging**
